// src/app/Disqus.jsx
import React from 'react';

/**
 *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
 *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
 */

var disqus_config = function () {
    this.page.url = 'https://daggerok.github.io/';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = 'root.daggerok.github.io'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function () { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://daggerok.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();

export default () => (
    <div>
        <p>yept</p>
        <div id="disqus_thread"></div>
        <noscript>
            Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
        </noscript>
        <script id="dsq-count-scr" src="https://daggerok.disqus.com/count.js" async></script>
    </div>
);

// src/app/disqus/disqus.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-disqus',
  templateUrl: './disqus.component.html',
  styleUrls: ['./disqus.component.less']
})
export class DisqusComponent implements OnInit {
  constructor() { }
  ngOnInit() { }
}

<p>Are discuss here?</p>
<div id="disqus_thread"></div>
<script>
  /**
   *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
   *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
   */
  var disqus_config = function () {
    this.page.url = 'https://daggerok.github.io/';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = 'root.daggerok.github.io'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };
  (function () { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://daggerok.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>
  Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>
<script id="dsq-count-scr" src="https://daggerok.disqus.com/count.js" async></script>
